#pragma once

// Embedded HTML/CSS/JS for the CSIght web radar UI
// Served directly from ESP32 flash over HTTP
// Minified to keep size small — target < 8KB

static const char CSIGHT_WEB_UI[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>"
"<title>CSIght Radar</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{background:#050505;color:#00ff88;font-family:'Courier New',monospace;height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;overflow:hidden}"
"#header{width:100%;padding:12px 16px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #00ff8822}"
"#title{font-size:22px;font-weight:bold;letter-spacing:2px;text-shadow:0 0 10px #00ff88}"
"#status{font-size:11px;opacity:0.5;letter-spacing:1px}"
"#status.connected{color:#00ff88;opacity:0.8}"
"#status.disconnected{color:#ff4444;opacity:0.8}"
"#session-stats{font-size:10px;opacity:0.4;letter-spacing:1px;padding:4px 16px;text-align:right}"
"#alert-panel{width:min(90vw,360px);margin-top:8px;padding:8px;border:1px solid #00ff8822;border-radius:4px;display:flex;align-items:center;gap:8px;font-size:11px}"
"#alert-panel.armed{border-color:#ff4444;box-shadow:0 0 6px #ff444455}"
"#alert-panel.triggered{background:#ff4444;color:#050505;animation:pulse 0.5s infinite alternate}"
"@keyframes pulse{from{opacity:1}to{opacity:0.6}}"
"#arm-btn{padding:4px 10px;border:1px solid #00ff8855;background:transparent;color:#00ff88;font-family:'Courier New',monospace;font-size:10px;border-radius:3px;cursor:pointer;letter-spacing:1px}"
"#arm-btn.armed{background:#ff4444;border-color:#ff4444;color:#050505;font-weight:bold}"
"#alert-thresh{width:50px;background:transparent;border:1px solid #00ff8855;color:#00ff88;font-family:'Courier New',monospace;font-size:10px;padding:2px;border-radius:3px}"
"#fw-panel{width:min(90vw,360px);margin-top:16px;padding:10px;border:1px dashed #00ff8833;border-radius:4px;font-size:11px}"
"#fw-panel summary{cursor:pointer;opacity:0.6;letter-spacing:1px}"
"#fw-status{margin-top:8px;opacity:0.6;font-size:10px;word-break:break-word}"
"#fw-panel input[type=file]{color:#00ff88;font-size:10px;margin-top:8px}"
"#fw-panel button{margin-top:8px;padding:5px 12px;border:1px solid #00ff8855;background:transparent;color:#00ff88;font-family:'Courier New',monospace;font-size:10px;border-radius:3px;cursor:pointer}"
"#main{display:flex;flex-direction:column;align-items:center;width:100%;flex:1;padding:12px}"
"#radar-wrap{position:relative;width:min(90vw,360px);height:min(90vw,360px)}"
"canvas#radar{width:100%;height:100%;display:block}"
"#controls{display:flex;gap:10px;margin-top:10px;width:min(90vw,360px)}"
".btn{flex:1;padding:10px;border:1px solid #00ff8855;background:#00ff8808;color:#00ff88;font-family:'Courier New',monospace;font-size:13px;letter-spacing:1px;cursor:pointer;border-radius:4px;transition:all 0.2s}"
".btn:hover{background:#00ff8822;border-color:#00ff88}"
".btn.active{background:#00ff8833;border-color:#00ff88;box-shadow:0 0 8px #00ff8844}"
"#info{display:flex;gap:16px;margin-top:10px;width:min(90vw,360px)}"
".info-box{flex:1;border:1px solid #00ff8822;padding:8px;border-radius:4px;text-align:center}"
".info-label{font-size:10px;opacity:0.5;letter-spacing:1px;margin-bottom:4px}"
".info-val{font-size:18px;font-weight:bold}"
"#sens-wrap{display:flex;align-items:center;gap:8px;margin-top:10px;width:min(90vw,360px)}"
"#sens-label{font-size:11px;opacity:0.5;white-space:nowrap}"
"#sens{flex:1;accent-color:#00ff88}"
"#sens-val{font-size:13px;min-width:20px;text-align:right}"
"#mode-wrap{display:flex;gap:6px;margin-top:8px;width:min(90vw,360px)}"
".mode-btn{flex:1;padding:7px 4px;border:1px solid #00ff8833;background:transparent;color:#00ff8888;font-family:'Courier New',monospace;font-size:11px;letter-spacing:1px;cursor:pointer;border-radius:3px;transition:all 0.2s}"
".mode-btn.active{background:#00ff8822;border-color:#00ff88;color:#00ff88;box-shadow:0 0 6px #00ff8833}"
"#waterfall-wrap{width:min(90vw,360px);margin-top:8px;display:none}"
"canvas#waterfall{width:100%;height:80px;display:block;border:1px solid #00ff8822;border-radius:4px}"
"#vitals-wrap{width:min(90vw,360px);margin-top:8px;display:none;flex-direction:column;gap:10px}"
".vital-row{border:1px solid #00ff8822;border-radius:4px;padding:10px}"
".vital-label{font-size:11px;opacity:0.5;letter-spacing:1px;margin-bottom:4px}"
".vital-val{font-size:24px;font-weight:bold}"
".vital-bar{height:6px;background:#00ff8815;border-radius:3px;margin-top:6px;overflow:hidden}"
".vital-bar-fill{height:100%;background:#00ff88;box-shadow:0 0 6px #00ff8888;transition:width 0.5s}"
"#mesh-wrap{width:min(90vw,360px);margin-top:8px;display:none}"
"canvas#mesh{width:100%;height:240px;display:block;border:1px solid #00ff8822;border-radius:4px;background:#00ff8805}"
"#history-wrap{width:min(90vw,360px);margin-top:8px;display:none}"
"canvas#history{width:100%;height:160px;display:block;border:1px solid #00ff8822;border-radius:4px}"
"#history-note{font-size:10px;opacity:0.4;margin-top:4px;text-align:center}"
"#node-toast{position:fixed;top:16px;left:50%;transform:translateX(-50%);background:#00ff88;color:#050505;padding:8px 16px;border-radius:4px;font-size:13px;font-weight:bold;letter-spacing:1px;opacity:0;transition:opacity 0.3s;pointer-events:none;z-index:100}"
"#target-flash{position:fixed;top:0;left:0;width:100%;height:100%;background:#00ff88;opacity:0;pointer-events:none;transition:opacity 0.1s;z-index:99}"
"</style>"
"</head>"
"<body>"
"<div id='target-flash'></div>"
"<div id='node-toast'></div>"
"<div id='header'>"
"  <span id='title'>CSIght</span>"
"  <span id='status' class='disconnected'>DISCONNECTED</span>"
"</div>"
"<div id='session-stats'>00:00 &middot; 0 events</div>"
"<div id='main'>"
"  <div id='alert-panel'>"
"    <button id='arm-btn' onclick='toggleArm()'>ARM</button>"
"    <span>Threshold:</span>"
"    <input type='number' id='alert-thresh' value='180' min='0' max='255' onchange='setAlertThresh(this.value)'>"
"    <span id='alert-status' style='margin-left:auto;opacity:0.5'>Disarmed</span>"
"  </div>"
"  <div id='radar-wrap'><canvas id='radar'></canvas></div>"
"  <div id='mode-wrap'>"
"    <button class='mode-btn active' onclick='setMode(0)'>RADAR</button>"
"    <button class='mode-btn' onclick='setMode(1)'>WATERFALL</button>"
"    <button class='mode-btn' onclick='setMode(2)'>PROXIMITY</button>"
"    <button class='mode-btn' onclick='setMode(3)'>VITALS</button>"
"    <button class='mode-btn' onclick='setMode(4)'>MESH</button>"
"    <button class='mode-btn' onclick='setMode(5)'>HISTORY</button>"
"  </div>"
"  <div id='waterfall-wrap'><canvas id='waterfall'></canvas></div>"
"  <div id='vitals-wrap'>"
"    <div class='vital-row'>"
"      <div class='vital-label'>BREATHING</div>"
"      <div class='vital-val' id='breath-val'>--</div>"
"      <div class='vital-bar'><div class='vital-bar-fill' id='breath-bar' style='width:0%'></div></div>"
"    </div>"
"    <div class='vital-row'>"
"      <div class='vital-label'>HEART RATE (EXPERIMENTAL)</div>"
"      <div class='vital-val' id='heart-val'>--</div>"
"      <div class='vital-bar'><div class='vital-bar-fill' id='heart-bar' style='width:0%'></div></div>"
"    </div>"
"  </div>"
"  <div id='mesh-wrap'><canvas id='mesh'></canvas></div>"
"  <div id='history-wrap'>"
"    <canvas id='history'></canvas>"
"    <div id='history-note'>Session only — resets on page reload</div>"
"  </div>"
"  <div id='info'>"
"    <div class='info-box'><div class='info-label'>MOTION</div><div class='info-val' id='motion-val'>--</div></div>"
"    <div class='info-box'><div class='info-label'>PROXIMITY</div><div class='info-val' id='prox-val'>--%</div></div>"
"    <div class='info-box'><div class='info-label'>TARGETS</div><div class='info-val' id='hit-val'>0</div></div>"
"  </div>"
"  <div id='sens-wrap'>"
"    <span id='sens-label'>SENSITIVITY</span>"
"    <input type='range' id='sens' min='0' max='10' value='5' oninput='setSens(this.value)'>"
"    <span id='sens-val'>5</span>"
"  </div>"
"  <details id='fw-panel'>"
"    <summary>FIRMWARE UPDATE</summary>"
"    <input type='file' id='fw-file' accept='.bin'>"
"    <br><button onclick='uploadFirmware()'>Upload &amp; Reboot</button>"
"    <div id='fw-status'></div>"
"  </details>"
"</div>"
"<script>"
"const W=360,H=360,CX=180,CY=180,R=160;"
"const radar=document.getElementById('radar');"
"const rctx=radar.getContext('2d');"
"radar.width=W;radar.height=H;"
"const wfc=document.getElementById('waterfall');"
"const wctx=wfc.getContext('2d');"
"wfc.width=360;wfc.height=80;"
"const meshc=document.getElementById('mesh');"
"const mctx=meshc.getContext('2d');"
"meshc.width=360;meshc.height=240;"
"const histc=document.getElementById('history');"
"const hctx=histc.getContext('2d');"
"histc.width=360;histc.height=160;"
"let motionHist=[];" // {t,intensity,breath,heart}
"const HIST_WINDOW_MS=120000;" // 2 minutes
"let sweep=0,blips=[],hits=0,mode=0,motionVal=0,proxVal=0;"
"let wsReady=false,ws=null;"
// Session stats — browser-local, resets on page reload (mirrors Flipper's
// own session tracking, which is separate and persists to its SD log)
"let sessionStart=Date.now(),eventCount=0;"
// Browser-side tripwire — entirely local, no ESP32 involvement needed since
// motion packets already stream continuously. Auto-resets 5s after firing,
// same behaviour as the Flipper's own alert mode.
"let armed=false,alertThresh=180,alertTriggered=false,alertTs=0;"
"const GREEN='#00ff88';"

// Blip object pool
"function addBlip(intensity,proximity){"
"  const angle=sweep*(Math.PI/32);"
"  const dist=R*0.1+R*0.85*(1-(proximity/100));"
"  const jitter=(intensity&3)*0.05;"
"  blips.push({x:CX+Math.cos(angle+jitter)*dist,y:CY+Math.sin(angle+jitter)*dist,age:255,r:Math.max(3,intensity/40)});"
"  if(blips.length>20)blips.shift();"
"  hits++;document.getElementById('hit-val').textContent=hits;"
"}"

// Draw radar
"function drawRadar(){"
"  rctx.clearRect(0,0,W,H);"
"  rctx.strokeStyle=GREEN;"
"  rctx.shadowBlur=8;rctx.shadowColor=GREEN;"
"  // Rings"
"  [R,R*0.66,R*0.33].forEach(r=>{"
"    rctx.globalAlpha=0.25+0.15*(R/r-1)*0.33;"
"    rctx.beginPath();rctx.arc(CX,CY,r,0,Math.PI*2);rctx.stroke();"
"  });"
"  // Crosshairs"
"  rctx.globalAlpha=0.12;rctx.lineWidth=0.5;"
"  rctx.beginPath();rctx.moveTo(CX-R,CY);rctx.lineTo(CX+R,CY);rctx.stroke();"
"  rctx.beginPath();rctx.moveTo(CX,CY-R);rctx.lineTo(CX,CY+R);rctx.stroke();"
"  // Sweep"
"  const a=sweep*(Math.PI/32);"
"  rctx.globalAlpha=1;rctx.lineWidth=2;"
"  rctx.beginPath();rctx.moveTo(CX,CY);"
"  rctx.lineTo(CX+Math.cos(a)*R,CY+Math.sin(a)*R);rctx.stroke();"
"  // Trail"
"  for(let t=1;t<=6;t++){"
"    const ta=a-t*0.08;"
"    rctx.globalAlpha=0.3-(t*0.04);"
"    rctx.lineWidth=2-t*0.25;"
"    rctx.beginPath();rctx.moveTo(CX,CY);"
"    rctx.lineTo(CX+Math.cos(ta)*(R-t*8),CY+Math.sin(ta)*(R-t*8));rctx.stroke();"
"  }"
"  // Blips"
"  blips.forEach(b=>{"
"    const alpha=b.age/255;"
"    rctx.globalAlpha=alpha;"
"    rctx.fillStyle=GREEN;"
"    rctx.shadowBlur=b.age>150?12:4;"
"    rctx.beginPath();rctx.arc(b.x,b.y,b.r*(0.5+alpha*0.5),0,Math.PI*2);rctx.fill();"
"    b.age=Math.max(0,b.age-3);"
"  });"
"  blips=blips.filter(b=>b.age>0);"
"  // Center"
"  rctx.globalAlpha=1;rctx.shadowBlur=10;"
"  rctx.beginPath();rctx.arc(CX,CY,4,0,Math.PI*2);rctx.fill();"
"  rctx.shadowBlur=0;rctx.globalAlpha=1;"
"}"

// Draw proximity
"function drawProximity(){"
"  rctx.clearRect(0,0,W,H);"
"  rctx.strokeStyle=GREEN;rctx.fillStyle=GREEN;"
"  rctx.shadowBlur=8;rctx.shadowColor=GREEN;"
"  const maxR=R*0.9;"
"  const r=maxR*(1-(proxVal/100))*0.8+maxR*0.1;"
"  [r,r+30,r+60].forEach((ar,i)=>{"
"    if(ar<=maxR){"
"      rctx.globalAlpha=0.6-i*0.15;"
"      rctx.lineWidth=1.5;"
"      rctx.beginPath();rctx.arc(CX,CY,ar,0,Math.PI*2);rctx.stroke();"
"    }"
"  });"
"  rctx.globalAlpha=1;"
"  rctx.beginPath();rctx.arc(CX,CY,6,0,Math.PI*2);rctx.fill();"
"  rctx.font='bold 32px Courier New';"
"  rctx.textAlign='center';"
"  rctx.fillText(proxVal+'%',CX,CY+60);"
"  rctx.font='13px Courier New';rctx.globalAlpha=0.5;"
"  rctx.fillText('PROXIMITY',CX,CY+80);"
"  rctx.globalAlpha=1;rctx.shadowBlur=0;"
"}"

// Waterfall
"const wfCols=[];const WF_MAX=360;"
"function pushWaterfall(bins){"
"  wfCols.push(bins);"
"  if(wfCols.length>WF_MAX)wfCols.shift();"
"  wctx.clearRect(0,0,360,80);"
"  wfCols.forEach((col,x)=>{"
"    col.forEach((v,y)=>{"
"      const brightness=Math.floor(v);"
"      if(brightness>30){"
"        const alpha=brightness/255;"
"        wctx.fillStyle=`rgba(0,255,136,${alpha})`;"
"        wctx.fillRect(x,y*(80/col.length),1,(80/col.length)+1);"
"      }"
"    });"
"  });"
"}"

// Target acquired flash
"function targetFlash(){"
"  const f=document.getElementById('target-flash');"
"  f.style.opacity='0.15';"
"  setTimeout(()=>f.style.opacity='0',400);"
"}"

// Node discovered toast
"function nodeToast(id){"
"  const t=document.getElementById('node-toast');"
"  t.textContent='NODE '+id+' DISCOVERED';"
"  t.style.opacity='1';"
"  setTimeout(()=>t.style.opacity='0',3000);"
"}"

// Browser-side tripwire controls
"function toggleArm(){"
"  armed=!armed;"
"  alertTriggered=false;"
"  const btn=document.getElementById('arm-btn');"
"  const panel=document.getElementById('alert-panel');"
"  const status=document.getElementById('alert-status');"
"  btn.textContent=armed?'DISARM':'ARM';"
"  btn.classList.toggle('armed',armed);"
"  panel.classList.toggle('armed',armed);"
"  panel.classList.remove('triggered');"
"  status.textContent=armed?'Armed':'Disarmed';"
"}"
"function setAlertThresh(v){alertThresh=parseInt(v)||180;}"
"function beep(){"
"  try{"
"    const ctx=new(window.AudioContext||window.webkitAudioContext)();"
"    const o=ctx.createOscillator(),g=ctx.createGain();"
"    o.connect(g);g.connect(ctx.destination);"
"    o.frequency.value=880;g.gain.value=0.15;"
"    o.start();o.stop(ctx.currentTime+0.15);"
"  }catch(e){}" // AudioContext may be blocked before first user interaction — fine to skip silently
"}"
"function checkAlert(intensity){"
"  if(!armed||alertTriggered){return;}"
"  if(intensity>=alertThresh){"
"    alertTriggered=true;alertTs=Date.now();"
"    document.getElementById('alert-panel').classList.add('triggered');"
"    document.getElementById('alert-status').textContent='TRIGGERED';"
"    beep();"
"  }"
"}"
"function updateSessionStats(){"
"  const s=Math.floor((Date.now()-sessionStart)/1000);"
"  const m=String(Math.floor(s/60)).padStart(2,'0');"
"  const sec=String(s%60).padStart(2,'0');"
"  document.getElementById('session-stats').textContent=m+':'+sec+' | '+eventCount+' events';"
"  if(alertTriggered&&Date.now()-alertTs>5000){"
"    alertTriggered=false;"
"    document.getElementById('alert-panel').classList.remove('triggered');"
"    document.getElementById('alert-status').textContent='Armed';"
"  }"
"}"
"setInterval(updateSessionStats,1000);"

// Mesh map — mirrors the Flipper's own multi-node map
"let meshNodes=[{x:0,y:0,active:false},{x:200,y:0,active:false},{x:200,y:200,active:false},{x:0,y:200,active:false}];"
"let meshEst=null;"
"function drawMesh(){"
"  mctx.clearRect(0,0,360,240);"
"  mctx.strokeStyle=GREEN;mctx.fillStyle=GREEN;"
"  let minX=0,maxX=0,minY=0,maxY=0;"
"  meshNodes.forEach(n=>{minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y);});"
"  const spanX=Math.max(1,maxX-minX),spanY=Math.max(1,maxY-minY);"
"  const pad=30;"
"  const toPx=(x,y)=>[pad+((x-minX)/spanX)*(360-pad*2),240-pad-((y-minY)/spanY)*(240-pad*2)];"
"  meshNodes.forEach((n,i)=>{"
"    const[px,py]=toPx(n.x,n.y);"
"    mctx.globalAlpha=n.active?1:0.3;"
"    mctx.beginPath();mctx.arc(px,py,6,0,Math.PI*2);"
"    if(n.active){mctx.fill();}else{mctx.stroke();}"
"    mctx.font='10px Courier New';mctx.textAlign='center';"
"    mctx.fillText('N'+i,px,py-12);"
"  });"
"  if(meshEst){"
"    const[ex,ey]=toPx(meshEst.x,meshEst.y);"
"    mctx.globalAlpha=(Date.now()/400)%2<1?1:0.2;"
"    mctx.lineWidth=2;"
"    mctx.beginPath();mctx.moveTo(ex-8,ey);mctx.lineTo(ex+8,ey);mctx.stroke();"
"    mctx.beginPath();mctx.moveTo(ex,ey-8);mctx.lineTo(ex,ey+8);mctx.stroke();"
"  }"
"  mctx.globalAlpha=1;"
"}"

// Rolling history chart — motion intensity (0-255) and vitals (BPM) over a
// fixed 2-minute session window. In-memory only: resets on page reload since
// this browser has no persistent storage of its own (the Flipper's SD log
// is a separate, longer-lived record — see the app's Settings menu for that).
"function pushHistory(intensity){"
"  const now=Date.now();"
"  motionHist.push({t:now,intensity:intensity});"
"  motionHist=motionHist.filter(s=>now-s.t<HIST_WINDOW_MS);"
"}"
"function drawHistory(){"
"  hctx.clearRect(0,0,360,160);"
"  hctx.strokeStyle=GREEN;hctx.fillStyle=GREEN;hctx.font='9px Courier New';"
"  hctx.globalAlpha=0.3;"
"  for(let g=0;g<=4;g++){"
"    const y=10+g*35;"
"    hctx.beginPath();hctx.moveTo(0,y);hctx.lineTo(360,y);hctx.stroke();"
"  }"
"  hctx.globalAlpha=1;"
"  if(motionHist.length<2){"
"    hctx.textAlign='center';hctx.fillText('Collecting data...',180,80);"
"    return;"
"  }"
"  const now=Date.now();"
"  const toX=t=>360-((now-t)/HIST_WINDOW_MS)*360;"
"  hctx.strokeStyle=GREEN;hctx.lineWidth=1.5;hctx.beginPath();"
"  motionHist.forEach((s,i)=>{"
"    const x=toX(s.t),y=150-(s.intensity/255)*140;"
"    if(i===0)hctx.moveTo(x,y);else hctx.lineTo(x,y);"
"  });"
"  hctx.stroke();"
"  hctx.textAlign='left';hctx.fillText('MOTION',4,12);"
"  hctx.textAlign='right';hctx.fillText('2 min ago',356,158);"
"  hctx.fillText('now',356,12);"
"}"

// Animation loop
"let lastSweep=0;"
"function loop(ts){"
"  if(ts-lastSweep>33){sweep=(sweep+1)%64;lastSweep=ts;"
"    if(mode===0)drawRadar();"
"    else if(mode===2)drawProximity();"
"    else if(mode===4)drawMesh();"
"    else if(mode===5)drawHistory();"
"  }"
"  requestAnimationFrame(loop);"
"}"
"requestAnimationFrame(loop);"

// WebSocket
"function connect(){"
"  ws=new WebSocket('ws://'+location.hostname+'/ws');"
"  ws.binaryType='arraybuffer';"
"  ws.onopen=()=>{"
"    wsReady=true;"
"    document.getElementById('status').textContent='CONNECTED';"
"    document.getElementById('status').className='connected';"
"  };"
"  ws.onclose=()=>{"
"    wsReady=false;"
"    document.getElementById('status').textContent='RECONNECTING';"
"    document.getElementById('status').className='disconnected';"
"    setTimeout(connect,2000);"
"  };"
"  ws.onmessage=e=>{"
"    const d=new Uint8Array(e.data);"
"    const i16=(lo,hi)=>{const v=lo|(hi<<8);return v>32767?v-65536:v;};"
"    if(d[0]===0x01){" // motion
"      motionVal=d[1];proxVal=d[2];"
"      document.getElementById('motion-val').textContent=motionVal;"
"      document.getElementById('prox-val').textContent=proxVal+'%';"
"      addBlip(motionVal,proxVal);"
"      pushHistory(motionVal);"
"      eventCount++;"
"      checkAlert(motionVal);"
"      if(motionVal>180)targetFlash();"
"    }else if(d[0]===0x03){" // waterfall
"      const count=d[1];"
"      const bins=Array.from(d.slice(2,2+count));"
"      if(mode===1)pushWaterfall(bins);"
"    }else if(d[0]===0x04){" // vitals
"      const breath=d[1],heart=d[2];"
"      document.getElementById('breath-val').textContent=breath>0?breath+' BPM':'--';"
"      document.getElementById('heart-val').textContent=heart>0?heart+' BPM':'--';"
"      document.getElementById('breath-bar').style.width=Math.min(100,(breath/40)*100)+'%';"
"      document.getElementById('heart-bar').style.width=Math.min(100,(heart/180)*100)+'%';"
"    }else if(d[0]===0x05){" // mesh
"      const nodeCount=d[1];"
"      let p=2;"
"      const positions=[];"
"      for(let n=0;n<4;n++){"
"        positions.push({x:i16(d[p],d[p+1]),y:i16(d[p+2],d[p+3])});"
"        p+=4;"
"      }"
"      const hasEst=d[p++];"
"      const ex=i16(d[p],d[p+1]);p+=2;"
"      const ey=i16(d[p],d[p+1]);p+=2;"
"      const activeIds=new Set();"
"      for(let n=0;n<nodeCount;n++){"
"        activeIds.add(d[p]);"
"        p+=3;"
"      }"
"      meshNodes=positions.map((pos,idx)=>({x:pos.x,y:pos.y,active:activeIds.has(idx)}));"
"      meshEst=hasEst?{x:ex,y:ey}:null;"
"    }else if(d[0]===0x06){" // node discovered
"      nodeToast(d[1]);"
"    }"
"  };"
"}"
"connect();"

// Controls
"function setMode(m){"
"  mode=m;"
"  document.querySelectorAll('.mode-btn').forEach((b,i)=>b.classList.toggle('active',i===m));"
"  document.getElementById('radar-wrap').style.display=(m===0||m===2)?'block':'none';"
"  document.getElementById('waterfall-wrap').style.display=m===1?'block':'none';"
"  document.getElementById('vitals-wrap').style.display=m===3?'flex':'none';"
"  document.getElementById('mesh-wrap').style.display=m===4?'block':'none';"
"  document.getElementById('history-wrap').style.display=m===5?'block':'none';"
"  if(ws&&wsReady&&m<4)ws.send(JSON.stringify({cmd:'mode',val:m}));"
"}"
"function setSens(v){"
"  document.getElementById('sens-val').textContent=v;"
"  if(ws&&wsReady)ws.send(JSON.stringify({cmd:'sens',val:parseInt(v)}));"
"}"

// Firmware update — raw file bytes POSTed directly, no multipart needed
"function uploadFirmware(){"
"  const f=document.getElementById('fw-file').files[0];"
"  const status=document.getElementById('fw-status');"
"  if(!f){status.textContent='Choose a .bin file first';return;}"
"  if(!confirm('Flash '+f.name+' ('+Math.round(f.size/1024)+' KB) and reboot?'))return;"
"  status.textContent='Uploading... do not close this page';"
"  fetch('/update',{method:'POST',body:f})"
"    .then(r=>r.text())"
"    .then(t=>{"
"      status.textContent=t.includes('OK')?'Success! Rebooting — reconnect in ~10s':'Failed: '+t;"
"    })"
"    .catch(e=>{status.textContent='Upload failed: '+e.message;});"
"}"
"</script>"
"</body>"
"</html>";
